name: flutter_chatapp
description: Flutter Chat App

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: ^1.13.1

  firebase_auth: ^3.3.9

  cloud_firestore: ^3.1.10

  firebase_messaging: ^11.2.8

  firebase_storage: ^10.2.9

  flutter_native_splash: ^2.1.0

  flutter_gen: ^4.1.6

  flutter_svg: ^1.0.3

  google_sign_in: ^5.2.4

  flutter_local_notifications: ^9.4.0

  page_transition: ^2.0.5

  intl: ^0.17.0

  image_picker: ^0.8.4+11

  file_picker: ^4.5.1

  mime: ^1.0.1

  open_file: ^3.2.1

  flutter_chat_ui: ^1.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  build_runner:

  flutter_gen_runner:

  flutter_launcher_icons: "^0.9.2"

# cli: flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/images/flutter_chatapp_logo.png"
  android: true
  ios: true
  remove_alpha_ios: true

# cli: fluttergen -c pubspec.yaml
flutter_gen:
  integrations:
    flutter_svg: true

# cli: flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: '#f6f5fb'
  branding: assets/images/flutter_chatapp_logo.png
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/flutter_chatapp_logo.png
    - assets/images/placeholder_group_image.png

    - assets/svgs/google.svg