name: flutter_chatapp
description: Flutter Chat App

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: ^1.13.1

  firebase_auth: ^3.3.9

  cloud_firestore: ^3.1.10

  firebase_messaging: ^11.2.8

  firebase_storage: ^10.2.9

  flutter_native_splash: ^2.1.0

  flutter_gen: ^4.1.6

  flutter_svg: ^1.0.3

  google_sign_in: ^5.2.4

  flutter_local_notifications: ^9.4.0

  shared_preferences: ^2.0.13

  page_transition: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
