// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALB1yuNXd6P1zJALOFlfdgdnAGsKZftgk',
    appId: '1:1082068835392:web:10b2c6fbe48ca4abf013a5',
    messagingSenderId: '1082068835392',
    projectId: 'flutter-chatapp-e8fe6',
    authDomain: 'flutter-chatapp-e8fe6.firebaseapp.com',
    storageBucket: 'flutter-chatapp-e8fe6.appspot.com',
    measurementId: 'G-R8VDYNZBNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPw49w2qA8xguOhUX2rUjrQqvUfvk3yfc',
    appId: '1:1082068835392:android:eca5d4c690e62c1ef013a5',
    messagingSenderId: '1082068835392',
    projectId: 'flutter-chatapp-e8fe6',
    storageBucket: 'flutter-chatapp-e8fe6.appspot.com',
  );
}
